POST http:localhost:3000/api/auth/signup
Content-Type: application/json

{
    "id": "dediindra_one",
    "name": "Dedi Indrawan",
    "email": "dediindrawan812@gmail.com",
    "password": "123456",
    "roles[]": "ADMIN",
    "roles[]": "PM"
}